version: '3.8'

services:
  bot:
    build: .
    container_name: transcription_bot
    restart: always
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - bot_network

networks:
  bot_network:
    name: bot_network
    driver: bridge
